controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# new_category:
#     path: /category/newCat
#     controller: App\Controller\IndexController::newCategory
